import type { Metadata } from "next";
import { Urbanist, Syne } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { TenstackProviders } from "./tenstack-provider";

const urbanist = Urbanist({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-urbanist",
});

const syne = Syne({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-syne",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${urbanist.variable} ${syne.variable}`}>
      <TenstackProviders>
        <TooltipProvider>
          <Toaster />
          <Sonner />
          <body>
            {children}
          </body>
        </TooltipProvider>
      </TenstackProviders>
    </html>
  );
}
